remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Pomodoro Musei di Pesaro]
description: [Raccolta di documenti sui Musei di Pesaro per facilitare la comprensione delle opere]
show_downloads: [false]
